workflows:
  ios-workflow:
    name: Viaja con Aldia iOS

    environment:
      node: 16
      cocoapods: default
      xcode: latest
      vars:
        BUILD_DIR: "ios/App"

      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.viajaconaldia.id"

    scripts:
      - name: Install Node dependencies
        script: |
          npm install
          npm install -D @angular/cli
          npm install -g @ionic/cli

      - name: Build Ionic Angular
        script: |
          ionic build

      - name: Sync Capacitor with iOS
        script: |
          npx cap sync ios

      - name: Install Cocoapods
        working_directory: ios/App
        script: |
          pod install

      - name: Build iOS Release
        script: |
          xcodebuild \
            -workspace "ios/App/App.xcworkspace" \
            -scheme "App" \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/App.xcarchive archive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM"

          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            -exportPath $CM_BUILD_DIR/export \
            -exportOptionsPlist exportOptions.plist

    artifacts:
      - ios/App/build/**/*.ipa
      - ios/App/build/**/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_app_store: false
        submit_to_testflight: true