workflows:
  ios-workflow:
    name: Viaja con Aldia iOS

    environment:
      node: 16
      cocoapods: default

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.viajaconaldia.id

    scripts:
      - name: Install Node dependencies
        script: |
          npm install
          npm install -D @angular/cli
          npm install -g @ionic/cli

      - name: Build Angular
        script: |
          npm run build

      - name: Sync Capacitor with iOS
        script: |
          npx cap sync ios

      - name: Install Cocoapods
        working_directory: ios/App
        script: |
          pod install

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false