workflows:
  ios-workflow:
    name: Viaja con Aldia iOS 
    # ....
    environment:
      ios_signing:
        distribution_type: app_store # or: ad_hoc | development | enterprise
        bundle_identifier: com.viajaconaldia.id