workflows:
  ios-workflow:
    name: Viaja con Aldia iOS (Prebuilt)

    environment:
      node: 18
      cocoapods: default

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.viajaconaldia.id

    scripts:
      - name: Install Node dependencies
        script: |
          npm ci

      - name: Install CocoaPods
        working_directory: ios/App
        script: |
          pod install

      - name: Build iOS archive
        script: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            archive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM"

      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            -exportPath $CM_BUILD_DIR/export \
            -exportOptionsPlist exportOptions.plist

    artifacts:
      - $CM_BUILD_DIR/export/*.ipa
      - $CM_BUILD_DIR/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false